project_id = "veyocast-platform"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "500MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://localhost:3001",
  "http://localhost:3002",
  "http://127.0.0.1:3103/auth/confirm"
]
jwt_expiry = 3600
enable_signup = false

[auth.email.template.invite]
subject = "Je bent uitgenodigd voor VeyoCast"
content_path = "./supabase/templates/invite.html"

[auth.email.template.recovery]
subject = "Herstel je VeyoCast-wachtwoord"
content_path = "./supabase/templates/recovery.html"

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
