import { Button, DataTable, PageHeader, StatusPill } from "@veyocast/ui";
import { hasCapability } from "@veyocast/auth";
import { requireControlCapability } from "../../../../lib/control-session";
import { createControlAdminClient } from "../../../../lib/supabase/admin";
import { createBillingOverride, promoteBillingAccountLive } from "./actions";

export default async function PlatformBillingPage({searchParams}:{searchParams:Promise<{fout?:string;succes?:string}>}){
  const session=await requireControlCapability("platform.system.read");
  const params=await searchParams;
  const data=await loadBillingHealth(session.isLive);
  const canOverride=hasCapability(session.capabilities,"platform.tenant.lifecycle");
  const canPromoteLive=hasCapability(session.capabilities,"platform.user.manage");
  return <><PageHeader description="Privacyveilige operationele status van shadowfacturen, provider-outbox en reconciliation. Bedragen, factuuradressen en providerpayloads worden hier niet gelogd." eyebrow="Platform · Operations" status={{label:data.divergences?`${data.divergences} afwijkingen`:"Geen bekende divergentie",tone:data.divergences?"critical":"success"}} title="Billing health"/>
    {params.fout?<p className="notice notice--critical" role="alert">{params.fout}</p>:null}{params.succes?<p className="notice notice--success" role="status">{params.succes}</p>:null}
    {session.assuranceLevel!=="aal2"?<p className="notice notice--warning" role="status">Voor herstelacties, providerresync en tijdelijke overrides is een recente AAL2-verificatie verplicht. Deze pagina blijft alleen-lezen.</p>:null}
    <section className="workspace-section"><div className="workspace-section__header"><div><h2 className="workspace-section__title">Pipeline</h2><p className="work-panel__meta">Collection en Player-enforcement zijn afzonderlijke kill switches. Reconciliation moet gezond zijn vóór een cohort wordt uitgebreid.</p></div></div><DataTable caption="Gezondheid van de billingpipeline."><thead><tr><th scope="col">Onderdeel</th><th scope="col">Status</th><th scope="col">Aantal</th></tr></thead><tbody>
      <tr><td>Outbox wacht</td><td><StatusPill label={data.pendingOutbox?"Aandacht":"Gezond"} tone={data.pendingOutbox?"warning":"success"}/></td><td>{data.pendingOutbox}</td></tr>
      <tr><td>Mislukte pogingen</td><td><StatusPill label={data.failedAttempts?"Aandacht":"Gezond"} tone={data.failedAttempts?"critical":"success"}/></td><td>{data.failedAttempts}</td></tr>
      <tr><td>Grace tenants</td><td><StatusPill label={data.grace?"Herstel loopt":"Geen"} tone={data.grace?"warning":"neutral"}/></td><td>{data.grace}</td></tr>
      <tr><td>Restricted tenants</td><td><StatusPill label={data.restricted?"Beperkt":"Geen"} tone={data.restricted?"critical":"neutral"}/></td><td>{data.restricted}</td></tr>
    </tbody></DataTable></section>
    <section className="workspace-section"><div className="workspace-section__header"><div><h2 className="workspace-section__title">Laatste reconciliation</h2><p className="work-panel__meta">Providerobjecten worden uitsluitend via geauthenticeerde Mollie GET opnieuw gelezen.</p></div></div>{data.runs.length?<DataTable caption="Laatste provider-reconciliation-runs."><thead><tr><th scope="col">Modus</th><th scope="col">Periode</th><th scope="col">Controle</th><th scope="col">Status</th></tr></thead><tbody>{data.runs.map(run=><tr key={`${run.provider_mode}-${run.started_at}`}><td>{run.provider_mode}</td><td>{format(run.started_at)} – {run.finished_at?format(run.finished_at):"bezig"}</td><td>{run.checked_count} gecontroleerd · {run.mismatch_count} afwijkingen</td><td>{run.status}</td></tr>)}</tbody></DataTable>:<p>Nog geen reconciliation-run. Collection en enforcement horen uit te blijven.</p>}</section>
    {canOverride?<section className="workspace-section"><div className="workspace-section__header"><div><h2 className="workspace-section__title">Tijdgebonden hersteloverride</h2><p className="work-panel__meta">Alleen AAL2, maximaal 31 dagen, altijd geaudit. Een tijdelijke entitlement activeert nooit een nieuw billable scherm.</p></div></div><form action={createBillingOverride} className="form-grid"><label>Tenant-ID<input name="tenantId" required type="text"/></label><label>Type<select name="overrideType"><option value="temporary_entitlement">Tijdelijke Player-toegang</option><option value="collection_pause">Incasso pauzeren</option><option value="trial_extension">Trial tijdelijk verlengen</option></select></label><label>Duur in uren<input defaultValue="24" max="744" min="1" name="durationHours" required type="number"/></label><label>Motivatie<input maxLength={1000} minLength={8} name="reason" required type="text"/></label><Button type="submit" variant="primary">Override gecontroleerd toepassen</Button></form></section>:null}
    {canPromoteLive?<section className="workspace-section"><div className="workspace-section__header"><div><h2 className="workspace-section__title">Provider live-promotie</h2><p className="work-panel__meta">Alleen platform owner + AAL2. Test-ID's blijven als historie bestaan; een nieuwe live Customer wordt via de outbox gemaakt.</p></div></div><form action={promoteBillingAccountLive} className="form-grid"><label>Tenant-ID<input name="tenantId" required type="text"/></label><label>Motivatie en providerreadback<input maxLength={1000} minLength={8} name="reason" required type="text"/></label><Button type="submit" variant="destructive">Billing naar live promoveren</Button></form></section>:null}
  </>;
}

async function loadBillingHealth(isLive:boolean){if(!isLive)return {divergences:0,failedAttempts:0,grace:0,pendingOutbox:0,restricted:0,runs:[] as Run[]};const admin=createControlAdminClient();const [outbox,attempts,grace,restricted,runs]=await Promise.all([admin.from("billing_outbox").select("id",{count:"exact",head:true}).in("state",["pending","failed","uncertain"]),admin.from("billing_payment_attempts").select("id",{count:"exact",head:true}).eq("provider_status","failed"),admin.from("billing_subscriptions").select("id",{count:"exact",head:true}).eq("status","grace"),admin.from("billing_subscriptions").select("id",{count:"exact",head:true}).eq("status","restricted"),admin.from("billing_reconciliation_runs").select("provider_mode,started_at,finished_at,checked_count,mismatch_count,status").order("started_at",{ascending:false}).limit(20)]);const typed=(runs.data??[]) as Run[];return {divergences:typed[0]?.mismatch_count??0,failedAttempts:attempts.count??0,grace:grace.count??0,pendingOutbox:outbox.count??0,restricted:restricted.count??0,runs:typed};}
type Run={checked_count:number;finished_at:string|null;mismatch_count:number;provider_mode:string;started_at:string;status:string};
function format(value:string){return new Intl.DateTimeFormat("nl-NL",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Amsterdam"}).format(new Date(value))}
