import Link from "next/link";
import { hasCapability } from "@veyocast/auth";
import { Button, StatusPill } from "@veyocast/ui";
import { requireTenantControlSession } from "../../../../../lib/control-session";
import { createControlSupabaseClient } from "../../../../../lib/supabase/server";
import { PageHeader } from "../../../_components/shell-primitives";
import { createBillingAccount, startPaymentMethodSetup } from "./actions";
import styles from "./billing.module.css";

export default async function BillingPage({ searchParams }: { searchParams: Promise<{ fout?: string; succes?: string }> }) {
  const session = await requireTenantControlSession("tenant.billing.read");
  const params = await searchParams;
  const data = await loadBilling(session.tenantId, session.isLive);
  const canManage = session.isLive && hasCapability(session.capabilities,"tenant.billing.manage");
  return <>
    <PageHeader description="Transparante schermtelling, immutable facturen en een provider-hosted betaalmethode. Bestaande content blijft bij een betaalprobleem veilig bewaard." eyebrow={`${session.tenant} · Instellingen`} status={{ label: data.enabled ? "Gecontroleerde cohort" : "Nog niet geactiveerd", tone: data.enabled ? "info" : "neutral" }} title="Abonnement & facturatie" />
    <p><Link href="/dashboard/settings#abonnement">← Terug naar instellingen</Link></p>
    {params.fout?<p className="notice notice--critical" role="alert"><strong>Actie mislukt.</strong> {params.fout}</p>:null}
    {params.succes?<p className="notice notice--success" role="status">{params.succes}</p>:null}
    {!data.enabled?<p className="notice notice--warning" role="status"><strong>Shadowmodus.</strong> Het schema en de schermtelling zijn beschikbaar, maar incasso en Player-enforcement blijven uit tot een expliciete tenantcohort en gezonde reconciliation.</p>:null}
    <div className={styles.grid}>
      <section className={styles.panel}><div className={styles.heading}><div><h2>Planstatus</h2><p>€ 5,95 incl. btw per actief billable scherm per maand, na 14 dagen trial.</p></div><StatusPill label={statusLabel(data.subscription?.status)} tone={statusTone(data.subscription?.status)} /></div>
        {data.subscription?<><dl className={styles.metrics}><div><dt>Billable schermen</dt><dd>{data.intervals.length}</dd></div><div><dt>Prijs per maand</dt><dd>{euro(data.intervals.length*595)}</dd></div><div><dt>Provider</dt><dd>{data.account?.provider_mode === "live" ? "Live" : "Testmodus"}</dd></div></dl><p>{billingPeriod(data.subscription)}</p></>:<p>Maak eerst het juridische billingaccount gereed. De trial start pas bij de eerste succesvolle billable Player-activatie.</p>}
      </section>
      <section className={styles.panel}><h2>Profiel & betaalmethode</h2>{data.account?<><dl><dt>Juridische naam</dt><dd>{data.account.legal_name}</dd><dt>Factuurmail</dt><dd>{data.account.invoice_email}</dd><dt>Beschikbaar krediet</dt><dd>{euro(Number(data.account.credit_balance_cents))}</dd></dl><p>{data.account.mollie_customer_id?`Mollie Customer is veilig gekoppeld · ${data.attempt?.provider_status??"geen open poging"}.`:"Mollie Customer wordt via de transactionele outbox voorbereid."}</p>{data.attempt?.checkout_url?<Button asChild variant="primary"><a href={data.attempt.checkout_url}>Open beveiligde Mollie-checkout</a></Button>:canManage&&data.account.mollie_customer_id?<form action={startPaymentMethodSetup}><input name="rowVersion" type="hidden" value={data.account.row_version}/><Button type="submit" variant="primary">Betaalmethode koppelen</Button></form>:null}</>:canManage?<form action={createBillingAccount} className={styles.form}><label>Juridische naam<input defaultValue={session.tenant} maxLength={180} minLength={2} name="legalName" required/></label><label>Factuurmail<input maxLength={254} name="invoiceEmail" required type="email"/></label><label className={styles.check}><input name="termsAccepted" required type="checkbox"/><span>Ik accepteer € 5,95 incl. btw per actief scherm per maand na 14 dagen trial.</span></label><Button type="submit" variant="primary">Billing gereedmaken</Button></form>:<p>Alleen een tenantbeheerder of eigenaar kan billing gereedmaken.</p>}</section>
    </div>
    <section className={styles.panel}><h2>Welke schermen tellen mee?</h2>{data.intervals.length?<ul className={styles.list}>{data.intervals.map((item)=><li key={item.id}><div><strong>{screenRelation(item.screens)?.name??"Scherm"}</strong><span>{screenRelation(item.screens)?.location??"Geen locatie"}</span></div><span>Billable sinds {formatDate(item.started_at)}</span></li>)}</ul>:<p>Nog geen billable scherminterval. Een draft of ongeclaimde koppelcode telt nooit mee.</p>}</section>
    {data.notifications.length?<section className={styles.panel}><h2>Betalingsmeldingen</h2><ul className={styles.list}>{data.notifications.map((notice)=><li key={notice.id}><div><strong>{notificationLabel(notice.stage)}</strong><span>{formatDate(notice.created_at)}</span></div><StatusPill label={notice.channel==="email"?(notice.state==="delivered"?"E-mail bezorgd":"E-mail gepland"):"In-app"} tone={notice.state==="failed"?"warning":"neutral"}/></li>)}</ul></section>:null}
    <section className={styles.panel}><h2>Facturen en betaalpogingen</h2>{data.invoices.length?<ul className={styles.list}>{data.invoices.map((invoice)=><li key={invoice.id}><div><strong>{invoice.invoice_number}</strong><span>{formatDate(invoice.period_start)} – {formatDate(invoice.period_end)}</span></div><span>{euro(Number(invoice.gross_cents))} · {invoice.status}</span></li>)}</ul>:<p>Er zijn nog geen facturen. Shadowberekeningen of drafts worden niet als echte schuld gepresenteerd.</p>}</section>
  </>;
}

async function loadBilling(tenantId:string|null,isLive:boolean){ if(!tenantId||!isLive)return {account:null,attempt:null,enabled:false,intervals:[],invoices:[],notifications:[],subscription:null}; const supabase=await createControlSupabaseClient(); if(!supabase)return {account:null,attempt:null,enabled:false,intervals:[],invoices:[],notifications:[],subscription:null}; const [flag,account,subscription,intervals,invoices,attempt,notifications]=await Promise.all([supabase.from("tenant_feature_flags").select("enabled").eq("tenant_id",tenantId).eq("flag_key","billing_engine_enabled").maybeSingle(),supabase.from("billing_accounts").select("id,provider_mode,mollie_customer_id,row_version,legal_name,invoice_email,credit_balance_cents").eq("tenant_id",tenantId).maybeSingle(),supabase.from("billing_subscriptions").select("status,trial_started_at,trial_ends_at,grace_ends_at,paid_through,current_period_start,current_period_end").eq("tenant_id",tenantId).neq("status","ended").maybeSingle(),supabase.from("screen_billing_intervals").select("id,started_at,ended_at,screens(name,location)").eq("tenant_id",tenantId).is("ended_at",null).order("started_at"),supabase.from("billing_invoices").select("id,invoice_number,period_start,period_end,gross_cents,status").eq("tenant_id",tenantId).order("period_start",{ascending:false}).limit(24),supabase.from("billing_payment_attempts").select("checkout_url,provider_status").eq("tenant_id",tenantId).eq("sequence_type","first").order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("billing_notifications").select("id,stage,channel,state,created_at").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(8)]); return {account:account.data,attempt:attempt.data,enabled:Boolean(flag.data?.enabled),intervals:intervals.data??[],invoices:invoices.data??[],notifications:notifications.data??[],subscription:subscription.data}; }
function euro(cents:number){return new Intl.NumberFormat("nl-NL",{currency:"EUR",style:"currency"}).format(cents/100)}
function formatDate(value:string){return new Intl.DateTimeFormat("nl-NL",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Amsterdam"}).format(new Date(value))}
function statusLabel(value?:string){return ({active:"Actief",draft:"Setup nodig",ended:"Beëindigd",grace:"Herstel nodig",restricted:"Beperkt",suspended:"Gepauzeerd",trialing:"Trial"} as Record<string,string>)[value??""]??"Nog niet gestart"}
function statusTone(value?:string){return value==="active"||value==="trialing"?"success":value==="grace"?"warning":value==="restricted"||value==="suspended"?"critical":"neutral" as const}
function screenRelation(value:{name:string;location:string|null}|Array<{name:string;location:string|null}>|null){return Array.isArray(value)?value[0]??null:value}
function notificationLabel(stage:string){return ({d0:"Betaling heeft aandacht nodig",d1:"Betalingsherinnering dag 1",d3:"Betalingsherinnering dag 3",d6:"Herstelperiode verloopt bijna",paid:"Betaalmethode bevestigd",recovered:"Toegang hersteld"} as Record<string,string>)[stage]??"Billingupdate"}
function billingPeriod(subscription:{current_period_end:string|null;current_period_start:string|null;grace_ends_at:string|null;status:string;trial_ends_at:string|null}){if(subscription.status==="trialing"&&subscription.trial_ends_at)return `Trial tot ${formatDate(subscription.trial_ends_at)}.`;if(subscription.status==="grace"&&subscription.grace_ends_at)return `Herstelperiode tot ${formatDate(subscription.grace_ends_at)}.`;if(subscription.current_period_start&&subscription.current_period_end)return `Factuurperiode ${formatDate(subscription.current_period_start)} – ${formatDate(subscription.current_period_end)}.`;return "De eerste factuurperiode start na de trial."}
